apiVersion: v1
kind: Service
metadata:
  name: klaverjas-service
  namespace: klaverjassen
spec:
  type: NodePort  # or LoadBalancer if using a cloud setup
  selector:
    app: klaverjas-app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080  # only needed for NodePort