apiVersion: apps/v1
kind: Deployment
metadata:
  name: curatool
  namespace: curatool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: curatool
  template:
    metadata:
      labels:
        app: curatool
    spec:
      imagePullSecrets:
        - name: ghcr-login
      containers:
        - name: curatool
          image: ghcr.io/gemberkoekje/thecuratool:a72b00c5b092ea6d0ef78debc91f62883a4adbdc
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Production
            - name: ConnectionStrings__Postgres
              valueFrom:
                secretKeyRef:
                  name: curatool-secrets
                  key: CONNECTION_STRING
            - name: Database__AutoMigrate
              valueFrom:
                configMapKeyRef:
                  name: curatool-web-config
                  key: Database__AutoMigrate
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 6
