apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: bot-on-the-clocktower-secrets
  namespace: bot-on-the-clocktower
spec:
  itemPath: "vaults/Gembercluster/items/bot-on-the-clocktower-secrets"
