apiVersion: apps/v1
kind: Deployment
metadata:
  name: ebi-cs-frontend
  namespace: ebi-cs-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ebi-cs-frontend
  template:
    metadata:
      labels:
        app: ebi-cs-frontend
    spec:
      imagePullSecrets:
        - name: ghcr-login
      containers:
        - name: ebi-cs-frontend
          image: ghcr.io/eosfrontier/ebi-cs-frontend:0.1.0-24
          securityContext:
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 5
