apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  interval: 10m
  chart:
    spec:
      chart: external-secrets
      version: "0.17.0"
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: flux-system
  values:
    webhook:
      port: 8443
      containerPort: 8443
    service:
      ports:
        - name: webhook
          port: 443
          targetPort: 8443