apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  interval: 10m
  chart:
    spec:
      chart: external-secrets
      version: "0.17.0" # Use the latest stable version or your preferred version
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: flux-system
  values: {}