apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vault
  namespace: flux-system
spec:
  interval: 10m
  chart:
    spec:
      chart: vault
      version: "1.19.4" # Use latest stable version or your preferred version
      sourceRef:
        kind: HelmRepository
        name: hashicorp
        namespace: flux-system
  values:
    server:
      dev:
        enabled: true # For testing/dev only. For production, set up HA and disable dev mode.
      dataStorage:
        enabled: true
        size: 5Gi