apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vault
  namespace: flux-system
spec:
  interval: 10m
  chart:
    spec:
      chart: vault
      version: "0.30.0" # Use latest stable version or your preferred version
      sourceRef:
        kind: HelmRepository
        name: hashicorp
        namespace: flux-system
  values:
    server:
      ha:
        enabled: true
        replicas: 1 # Increase for HA
        raft:
          enabled: true
          setNodeId: true
          config: |
            cluster_name = "vault-integrated-storage"
            storage "raft" {
              path    = "/vault/data"
              node_id = "vault-0"
            }
            listener "tcp" {
              address     = "0.0.0.0:8200"
              cluster_address = "0.0.0.0:8201"
              tls_disable = 1
            }
            ui = true
      dataStorage:
        enabled: true
        size: 5Gi
      ui:
        enabled: true
    primary:
      persistence:
        enabled: true
        size: 8Gi
        storageClass: "local-path" # Set to your desired StorageClass, or leave empty for default