apiVersion: v1
kind: Service
metadata:
  name: vault
  namespace: flux-system
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.232   # <-- Add this line
  ports:
    - port: 8200
      targetPort: 8200
      protocol: TCP
      name: vault
  selector:
    app.kubernetes.io/name: vault