# debug-pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: debug
  namespace: flux-system
spec:
  containers:
  - name: debug
    image: nicolaka/netshoot
    command: ["sleep", "3600"]
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop: ["ALL"]
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault
  restartPolicy: Never