apiVersion: v1
kind: Service
metadata:
  name: mysql-loadbalancer
  namespace: mysql
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.233   # <-- Add this line
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
      name: mysql
  selector:
    app: mysql