apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  namespace: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: phpmyadmin:5
          ports:
            - containerPort: 80
          env:
            - name: PMA_HOST
              value: mysql-deploy
            - name: PMA_PORT
              value: "3306"
            - name: PMA_ABSOLUTE_URI
              value: http://192.168.1.230/phpmyadmin/
---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  namespace: mysql
spec:
  selector:
    app: phpmyadmin
  ports:
    - port: 80
      targetPort: 80