apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: connect
  namespace: flux-system
spec:
  interval: 10m
  chart:
    spec:
      chart: connect
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: onepassword
        namespace: flux-system
  values:
    operator:
      create: true
    connect:
      credentialsPath: /etc/1password/credentials.json
    extraVolumes:
      - name: credentials
        secret:
          secretName: 1password-credentials
    extraVolumeMounts:
      - name: credentials
        mountPath: /etc/1password
        readOnly: true
  valuesFrom:
    - kind: Secret
      name: 1password-token-value
      valuesKey: token
      targetPath: operator.token.value
      optional: false
  # Make sure the Secret exists in the same namespace