apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: connect
  namespace: flux-system
spec:
  interval: 10m
  chart:
    spec:
      chart: connect
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: onepassword
        namespace: flux-system
  values:
    operator:
      create: true
  # Make sure the Secret exists in the same namespace