apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: onepassword-secrets-injector
  namespace: flux-system
spec:
  interval: 10m
  chart:
    spec:
      chart: secrets-injector
      version: "1.1.0" # or latest stable
      sourceRef:
        kind: HelmRepository
        name: onepassword
        namespace: flux-system
  values: {}