apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: onepassword
  namespace: flux-system
spec:
  interval: 1h
  url: https://github.com/1Password/connect-helm-charts/tree/main/charts/secrets-injector