apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: traefik-charts
  namespace: flux-system
spec:
  url: https://traefik.github.io/charts
  interval: 10m0s
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: traefik-crds
  namespace: flux-system
spec:
  interval: 1h
  url: https://github.com/traefik/traefik
  ref:
    tag: v3.4.3
