apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adventureengine-dataprotection-qnap
  namespace: adventureengine
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: qnap-nfs
  resources:
    requests:
      storage: 100Mi
