apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dungeontable-uploads-qnap
  namespace: dungeontable
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: qnap-nfs
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dungeontable-dataprotection-qnap
  namespace: dungeontable
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: qnap-nfs
  resources:
    requests:
      storage: 100Mi
