apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: file-server-pvc-qnap
  namespace: file-server
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: qnap-nfs
  resources:
    requests:
      storage: 32Gi
