apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: klaverjas-content
  namespace: klaverjassen
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path # or your preferred storage class