apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vortexplotboek-dataprotection-qnap
  namespace: vortexplotboek
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: qnap-nfs
  resources:
    requests:
      storage: 100Mi
