apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vscode-tunnel-pvc-longhorn
  namespace: vscode-tunnel
  annotations:
    longhorn.io/volume-number-of-replicas: "1"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 50Gi
