apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: kube-system
spec:
  interval: 10m0s
  releaseName: traefik
  chart:
    spec:
      chart: traefik
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: traefik-charts
        namespace: flux-system
  values:
    additionalArguments:
      - "--certificatesresolvers.le.acme.email=Arie_Hofland@hotmail.com"
      - "--certificatesresolvers.le.acme.storage=/data/acme.json"
      - "--certificatesresolvers.le.acme.httpchallenge=true"
      - "--certificatesresolvers.le.acme.httpchallenge.entrypoint=web"
    persistence:
      enabled: true
      path: /data
      size: 1Gi
      accessMode: ReadWriteOnce
      storageClass: default
    # Add this block for proper volume mounting
    volumeMounts:
      - name: data
        mountPath: /data
    volumes:
      - name: data
        persistentVolumeClaim:
          claimName: traefik-acme
    ports:
      web:
        expose:
          enabled: true
        port: 80
        protocol: TCP
      websecure:
        expose:
          enabled: true
        port: 443
        protocol: TCP
    ingressRoute:
      dashboard:
        enabled: true
    logs:
      general:
        level: INFO
      access:
        enabled: true