apiVersion: apps/v1
kind: Deployment
metadata:
  name: armabotcs
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: armabotcs
  template:
    metadata:
      labels:
        app: armabotcs
      annotations:
        operator.1password.io/inject: "armabotcs"
    spec:
      containers:
        - name: armabotcs
          image: ghcr.io/gemberkoekje/armabotcs:1.0.0-37
          command: ["dotnet", "ArmaBotCs.dll"] # <-- Add this line (replace with your actual entrypoint)
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          env:
            - name: Discord__Token
              value: op://Gembercluster/discord-secret/token
            - name: ConnectionStrings__Postgres
              value: op://Gembercluster/postgress-secret/connectionstring