apiVersion: apps/v1
kind: Deployment
metadata:
  name: armabotcs
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: armabotcs
  template:
    metadata:
      labels:
        app: armabotcs
    spec:
      containers:
        - name: armabotcs
          image: ghcr.io/gemberkoekje/armabotcs:1.0.0-37
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          env:
            - name: Discord__Token
              valueFrom:
                secretKeyRef:
                  name: discord-secret
                  key: discord-token
            - name: ConnectionStrings__Postgres
              valueFrom:
                secretKeyRef:
                  name: postgresql-connection-secret
                  key: postgres-connectionstring
      imagePullSecrets:
        - name: ghcr-secret
