apiVersion: apps/v1
kind: Deployment
metadata:
  name: armabotcs
  namespace: armabotcs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: armabotcs
  template:
    metadata:
      labels:
        app: armabotcs
    spec:
      imagePullSecrets:
        - name: ghcr-login
      containers:
        - name: armabotcs
          image: ghcr.io/gemberkoekje/armabotcs:1.0.0-38
          command: ["dotnet", "ArmaBotCs.dll"] # <-- Add this line (replace with your actual entrypoint)
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          env:
            - name: ConnectionStrings__Postgres
              valueFrom:
                secretKeyRef:
                  name: postgress-secret
                  key: connectionstring
            - name: Discord__Token
              valueFrom:
                secretKeyRef:
                  name: discord-secret
                  key: token
