apiVersion: apps/v1
kind: Deployment
metadata:
  name: spacetraders-api
  namespace: spacetraders
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spacetraders-api
  template:
    metadata:
      labels:
        app: spacetraders-api
    spec:
      imagePullSecrets:
        - name: ghcr-login
      containers:
        - name: spacetraders-api
          image: ghcr.io/gemberkoekje/spacetraders-api:sha256:d61afb27c5dfcd7ddc024f6a3c4158d12564869fc3fd55de9a99e1b2cd68bf8b
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: spacetraders-config
            - secretRef:
                name: spacetraders-secrets
          startupProbe:
            httpGet:
              path: /health/startup
              port: 8080
            failureThreshold: 30
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8080
            periodSeconds: 20
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
