apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: my-ip-address-pool
  namespace: metallb-system
spec:
  dependsOn:
    - name: metallb-crds
  addresses:
  - 192.168.1.240-192.168.1.245