apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - metallb-namespace.yaml
  - metallb-helmrepository.yaml
  - config
  - metallb-release.yaml
  - nginx-namespace.yaml
  - nginx-lb-test.yaml
  