apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb-crds
  namespace: flux-system
spec:
  interval: 10m
  path: ./config/crd
  prune: true
  sourceRef:
    kind: GitRepository
    name: metallb-upstream
    namespace: flux-system
  wait: true
  timeout: 5m