apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb
  namespace: flux-system
spec:
  interval: 10m
  path: ./config/manifests/metallb-native.yaml
  prune: true
  sourceRef:
    kind: GitRepository
    name: metallb-upstream
    namespace: flux-system
  wait: true
  timeout: 5m
  targetNamespace: metallb-system