apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: metallb-upstream
  namespace: flux-system
spec:
  interval: 1h
  url: https://github.com/metallb/metallb
  ref:
    tag: v0.14.5