apiVersion: apps/v1
kind: Deployment
metadata:
  name: metallb-controller
  namespace: metallb-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metallb
  template:
    metadata:
      labels:
        app: metallb
    spec:
      containers:
      - name: controller
        image: metallb/controller:v0.10.3
        args:
        - --port=7472
        - --config=/etc/metallb/config
        volumeMounts:
        - name: config
          mountPath: /etc/metallb
      volumes:
      - name: config
        configMap:
          name: metallb-config
      serviceAccountName: metallb-controller