apiVersion: v1
kind: Service
metadata:
  name: nginx-lb
  namespace: nginx   # <-- Add this line
spec:
  selector:
    app: nginx
  ipFamilyPolicy: SingleStack
  ipFamilies:
    - IPv4
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: nginx   # <-- Add this line
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
