apiVersion: apps/v1
kind: Deployment
metadata:
  name: ebi-cs-api
  namespace: ebi-cs-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ebi-cs-api
  template:
    metadata:
      labels:
        app: ebi-cs-api
    spec:
      imagePullSecrets:
        - name: ghcr-login
      containers:
        - name: ebi-cs-api
          image: ghcr.io/eosfrontier/ebi-cs-api:1.0.0-21
          command: ["dotnet", "ebi-cs-api.webapi.dll"]
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          ports:
            - containerPort: 8080
          startupProbe:
            httpGet:
              path: /ebi-cs-api/health
              port: 8080
            failureThreshold: 18
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /ebi-cs-api/health
              port: 8080
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /ebi-cs-api/health
              port: 8080
            periodSeconds: 20
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          env:
            - name: ConnectionStrings__Postgres
              valueFrom:
                secretKeyRef:
                  name: postgress-ebi-secret
                  key: connectionstring
            - name: Discord__Token
              valueFrom:
                secretKeyRef:
                  name: discord-secret
                  key: token
            - name: BearerConfiguration__Key
              valueFrom:
                secretKeyRef:
                  name: bearer-secret
                  key: key

