apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: ebi-cs-api
  namespace: flux-system
spec:
  image: ghcr.io/eosfrontier/ebi-cs-api
  interval: 5m
  secretRef:
    name: ghcr-login
