# grafana-release.yaml
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  chart:
    spec:
      chart: grafana
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: monitoring
      version: "9.2.0"  # or latest stable
  interval: 5m
  values:
    replicaCount: 1   # <-- Add this line
    admin:
      existingSecret: grafana-secret
      passwordKey: grafana-password # Must match the secretKey in your ExternalSecret
    service:
      type: ClusterIP
    ingress:
      enabled: false
    persistence:
      enabled: true
      size: 10Gi
      storageClassName: "local-path"  # Set to your storage class if needed
      accessModes:
        - ReadWriteOnce
    grafana.ini:
      server:
        root_url: "%(protocol)s://%(domain)s/grafana/"
        serve_from_sub_path: true
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          - name: Prometheus
            type: prometheus
            access: proxy
            url: http://prometheus-server.monitoring.svc.cluster.local:80
            isDefault: true
    plugins:
      - grafana-piechart-panel
