# grafana-release.yaml
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  chart:
    spec:
      chart: grafana
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: monitoring
      version: "9.2.0"  # or latest stable
  interval: 5m
  values:
    replicaCount: 1   # <-- Add this line
    admin:
      adminPassword: 6wMSwhm7
    service:
      type: ClusterIP
    ingress:
      enabled: false
    persistence:
      enabled: true
      size: 10Gi
      storageClassName: "local-path"  # Set to your storage class if needed
      accessModes:
        - ReadWriteOnce
      name: grafana  # <-- Add this line
    grafana.ini:
      server:
        root_url: "%(protocol)s://%(domain)s/grafana/"
        serve_from_sub_path: true
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          - name: Prometheus
            type: prometheus
            access: proxy
            url: http://prometheus-server.monitoring.svc.cluster.local:80
            isDefault: true
          - name: Loki
            type: loki
            access: proxy
            url: http://loki.monitoring.svc.cluster.local:3100
            isDefault: false
    plugins:
      - grafana-piechart-panel
    initChownData:
      enabled: false
    env:
      GF_SECRETS_ENCRYPTION_PROVIDER: ""
