apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  chart:
    spec:
      chart: loki
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: monitoring
      version: "9.2.0" # Use the latest stable version or your preferred version
  interval: 5m
  values:
    persistence:
      enabled: true
      storageClassName: "local-path"
      size: 10Gi
    service:
      type: ClusterIP