apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana-loki
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      version: "*"
      chart: loki
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: monitoring
      interval: 60m
  values:
    deploymentMode: SingleBinary
    resultsCache:
      enabled: true
      allocatedMemory: 1024
      persistence:
        enabled: true
      statefulStrategy:
        type: RollingUpdate
      resources:
        requests:
          cpu: 100m
    chunksCache:
      enabled: true
      allocatedMemory: 1024
      persistence:
        enabled: true
      statefulStrategy:
        type: RollingUpdate
      resources:
        requests:
          cpu: 100m
    lokiCanary:
      enabled: false
    test:
      enabled: false
    loki:
      auth_enabled: false
      commonConfig:
        replication_factor: 1
      storage:
        type: 'filesystem'
      schemaConfig:
        configs:
        - from: "2024-01-01"
          store: tsdb
          index:
            prefix: loki_index_
            period: 24h
          object_store: filesystem
          schema: v13
      limits_config:
        allow_structured_metadata: true
        max_structured_metadata_size: 32MB
      ingester:
        chunk_encoding: zstd
    singleBinary:
      replicas: 1
      persistence:
        enabled: true
        storageClassName: "local-path"
        accessModes:
          - ReadWriteOnce
        size: 10Gi
    read:
      replicas: 0
    backend:
      replicas: 0
    write:
      replicas: 0