# infrastructure/ingress-nginx/ingress-nginx-release.yaml
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 10m
  chart:
    spec:
      chart: ingress-nginx
      version: "4.10.0"  # You can pin a version or leave it out
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  install:
    createNamespace: true
  values:
    controller:
      replicaCount: 1
      service:
        type: LoadBalancer  # Or use ClusterIP if you're using a bare-metal ingress solution like MetalLB
