apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ebi-cs-api-ingress
  namespace: ebi-cs-api
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx-public
  tls:
  - hosts:
    - gemberkoekje.nl
    secretName: ebi-cs-api-tls
  rules:
  - host: gemberkoekje.nl
    http:
      paths:
      - path: /ebi-cs-api
        pathType: Prefix
        backend:
          service:
            name: ebi-cs-api-service
            port:
              number: 80
  - host: 192.168.1.230
    http:
      paths:
      - path: /ebi-cs-api
        pathType: Prefix
        backend:
          service:
            name: ebi-cs-api-service
            port:
              number: 80