apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: phpmyadmin-ingress
  namespace: mysql
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: default-ip-whitelist@kubernetescrd
spec:
  stripPrefix:
    prefixes:
      - "/phpmyadmin"
  rules:
    - http:
        paths:
          - path: /phpmyadmin
            pathType: Prefix
            backend:
              service:
                name: phpmyadmin
                port:
                  number: 80