apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spacetraders-ingress
  namespace: spacetraders
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx-public
  tls:
  - hosts:
    - gemberkoekje.nl
    secretName: ebi-cs-api-tls
  rules:
  - host: gemberkoekje.nl
    http:
      paths:
      - path: (/spacetraders/api/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: spacetraders-api-service
            port:
              number: 80
      - path: (/spacetraders/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: spacetraders-app-service
            port:
              number: 80
