#!/usr/bin/env python3
"""Checks this repository the way Flux will read it. From the repository root:

    python3 scripts/validate.py

Needs PyYAML, and flux, kubeconform and helm on PATH (.github/workflows/validate.yaml pins them).

1. Every YAML/JSON file parses, without duplicate keys.
2. Every Flux Kustomization builds with `flux build kustomization`, as kustomize-controller does.
3. What they build passes kubeconform in strict mode: Kubernetes schemas, Flux's schemas for the
   Flux version in gotk-components.yaml, and the CRD catalog for the other custom resources.
4. Flux references resolve (sourceRefs, chartRefs, dependsOn, valuesFrom), and every manifest is
   applied by some Kustomization (a warning: commenting an app out of a kustomization is allowed).
5. YAML/JSON embedded in ConfigMaps parses, and Grafana's provisioning fits together: alert rules
   use data sources and dashboards that exist, and policies use contact points that exist.
6. Every HelmRelease renders with its chart and values (`helm template`), as helm-controller does,
   and the result passes kubeconform. Top-level values the chart doesn't have are a warning.
"""

import io
import json
import os
import re
import subprocess
import sys
import tarfile
import tempfile
import urllib.request

import yaml

# What the k3s stable channel (infrastructure/system-upgrade-plans) was on in October 2026.
KUBERNETES_VERSION = "1.36.0"
# Schemas for cert-manager, MetalLB, 1Password, Traefik and system-upgrade-controller resources.
# Pinned to a commit so CI doesn't change under you; bump it when adding a newer CRD version.
CRD_CATALOG = (
    "https://raw.githubusercontent.com/datreeio/CRDs-catalog/d373c2da9702bc9509a004db83e57263fe3bdfc1/"
    "{{.Group}}/{{.ResourceKind}}_{{.ResourceAPIVersion}}.json"
)
FLUX_COMPONENTS = "clusters/home/flux-system/gotk-components.yaml"
NOT_SYNTAX_CHECKED = ("graphify-out/",)  # generated by the graphify tool
NOT_MANIFESTS = ("graphify-out/", ".claude/", ".github/", "docs/")

problems = {"error": 0, "warning": 0}


def report(level, message, file=None, line=None):
    """Prints a problem; in GitHub Actions also as an annotation on the file."""
    problems[level] += 1
    if os.environ.get("GITHUB_ACTIONS") == "true":
        where = ",".join(p for p in (f"file={file}" if file else "", f"line={line}" if line else "") if p)
        text = message.replace("%", "%25").replace("\r", "%0D").replace("\n", "%0A")
        print(f"::{level}{' ' + where if where else ''}::{text}")
    else:
        location = f"{file}{f':{line}' if line else ''}: " if file else ""
        print(f"{level.upper()}: {location}{message}")


def section(title):
    print(f"\n== {title}", flush=True)


def run(cmd, stdin=None):
    # KUBECONFIG points nowhere: nothing here may talk to a cluster.
    env = dict(os.environ, KUBECONFIG=os.devnull)
    return subprocess.run(cmd, input=stdin, capture_output=True, text=True, env=env)


class Loader(yaml.SafeLoader):
    """SafeLoader that rejects duplicate keys, which YAML parsers otherwise silently overwrite."""

    def construct_mapping(self, node, deep=False):
        seen = set()
        for key_node, _ in node.value:
            if key_node.tag == "tag:yaml.org,2002:merge":
                continue  # `<<:` merge keys may repeat
            key = self.construct_object(key_node, deep=deep)
            if key in seen:
                raise yaml.MarkedYAMLError(
                    "while constructing a mapping", node.start_mark, f"found duplicate key {key!r}", key_node.start_mark
                )
            seen.add(key)
        return super().construct_mapping(node, deep)


def yaml_docs(text):
    return [d for d in yaml.load_all(text, Loader) if isinstance(d, dict)]


def parse_error(exc):
    """Message and 1-based line of a YAML or JSON parse error."""
    if isinstance(exc, json.JSONDecodeError):
        return exc.msg, exc.lineno
    mark = getattr(exc, "problem_mark", None)
    return str(exc).replace("\n", " "), mark.line + 1 if mark else None


def check_syntax(files):
    for f in files:
        if f.startswith(NOT_SYNTAX_CHECKED) or not f.endswith((".yaml", ".yml", ".json")):
            continue
        try:
            with open(f, encoding="utf-8") as fh:
                json.load(fh) if f.endswith(".json") else yaml_docs(fh.read())
        except (yaml.YAMLError, json.JSONDecodeError) as exc:
            message, line = parse_error(exc)
            report("error", message, f, line)


def manifests(files):
    """(file, document) for every Kubernetes object in the repository's own manifest files."""
    for f in files:
        if f.endswith((".yaml", ".yml")) and not f.startswith(NOT_MANIFESTS):
            with open(f, encoding="utf-8") as fh:
                try:
                    yield from ((f, d) for d in yaml_docs(fh.read()) if "kind" in d)
                except yaml.YAMLError:
                    pass  # already reported by check_syntax


def flux_schemas(directory):
    """Downloads Flux's JSON schemas for the installed Flux version; returns kubeconform's location."""
    with open(FLUX_COMPONENTS, encoding="utf-8") as fh:
        version = next((m.group(1) for line in fh if (m := re.match(r"# Flux Version: (v\S+)", line))), None)
    if not version:
        sys.exit(f"No '# Flux Version:' line in {FLUX_COMPONENTS}")
    url = f"https://github.com/fluxcd/flux2/releases/download/{version}/crd-schemas.tar.gz"
    with urllib.request.urlopen(url, timeout=60) as response:
        tarfile.open(fileobj=io.BytesIO(response.read()), mode="r:gz").extractall(directory, filter="data")
    print(f"Flux {version} schemas")
    return os.path.join(directory, "{{.ResourceKind}}{{.KindSuffix}}.json")


def kubeconform(stream, label, flux_location, cache, file=None, ignore_missing=False):
    # No schema for CustomResourceDefinition is published; ours come from `flux install` and charts.
    cmd = ["kubeconform", "-strict", "-summary", "-kubernetes-version", KUBERNETES_VERSION, "-cache", cache,
           "-skip", "CustomResourceDefinition",
           "-schema-location", "default", "-schema-location", flux_location, "-schema-location", CRD_CATALOG]
    result = run(cmd + (["-ignore-missing-schemas"] if ignore_missing else []) + ["-"], stream)
    summary = result.stdout.strip().splitlines()[-1:] or [""]
    if result.returncode:
        report("error", f"kubeconform rejects {label}:\n{result.stdout}{result.stderr}".strip(), file)
    else:
        print(f"  {label}: {summary[0].replace('Summary: ', '')}")


def build_kustomizations(kustomizations, flux_location, cache):
    """Builds every Flux Kustomization like kustomize-controller; returns all objects they apply."""
    objects = []
    for file, ks in kustomizations:
        name, path = ks["metadata"]["name"], ks["spec"]["path"]
        result = run(["flux", "build", "kustomization", name, "--path", path, "--kustomization-file", file, "--dry-run"])
        if result.returncode:
            report("error", f"flux build of Kustomization {name} ({path}) fails:\n{result.stderr.strip()}", file)
            continue
        kubeconform(result.stdout, f"Kustomization {name} ({path})", flux_location, cache, file)
        objects += yaml_docs(result.stdout)
    return objects


def check_references(objects, origin):
    """Flux fails these at reconcile time, after the change is already on main."""
    have = {(o["kind"], o["metadata"].get("namespace"), o["metadata"]["name"]) for o in objects}
    checked = 0

    for o in objects:
        kind, meta, spec = o["kind"], o["metadata"], o.get("spec") or {}
        ns, name = meta.get("namespace"), meta["name"]
        file = origin.get((kind, name))

        def need(ref_kind, ref_name, ref_ns, why, alternatives=()):
            nonlocal checked
            checked += 1
            if not any((k, ref_ns, ref_name) in have for k in (ref_kind, *alternatives)):
                report("error", f"{kind} {ns}/{name}: {why} {ref_kind} {ref_ns}/{ref_name} does not exist", file)

        if kind == "Kustomization" and o["apiVersion"].startswith("kustomize.toolkit.fluxcd.io/"):
            ref = spec["sourceRef"]
            need(ref["kind"], ref["name"], ref.get("namespace", ns), "sourceRef")
            for dep in spec.get("dependsOn") or []:
                need("Kustomization", dep["name"], dep.get("namespace", ns), "dependsOn")
        elif kind == "HelmRelease":
            chart = (spec.get("chart") or {}).get("spec")
            ref = chart["sourceRef"] if chart else spec["chartRef"]
            need(ref["kind"], ref["name"], ref.get("namespace", ns), "chart source")
            for dep in spec.get("dependsOn") or []:
                need("HelmRelease", dep["name"], dep.get("namespace", ns), "dependsOn")
            for values in spec.get("valuesFrom") or []:
                if not values.get("optional"):
                    # Secrets in this cluster come from 1Password: a OnePasswordItem creates one of the same name.
                    alternatives = ("OnePasswordItem",) if values["kind"] == "Secret" else ()
                    need(values["kind"], values["name"], ns, "valuesFrom", alternatives)
    print(f"  {checked} references checked")


def applied_files(kustomizations):
    """Repository files that some Flux Kustomization applies (directly, as a resource or generator input)."""
    used = set()

    def walk(directory):
        kfile = os.path.join(directory, "kustomization.yaml")
        if not os.path.isfile(kfile):
            # Flux generates a kustomization with every manifest below this directory.
            for entry in sorted(os.listdir(directory)):
                path = os.path.join(directory, entry)
                if os.path.isdir(path):
                    walk(path)
                elif entry.endswith((".yaml", ".yml")):
                    used.add(os.path.normpath(path))
            return
        used.add(os.path.normpath(kfile))
        with open(kfile, encoding="utf-8") as fh:
            k = yaml.safe_load(fh) or {}
        for ref in (k.get("resources") or []) + (k.get("components") or []):
            path = os.path.normpath(os.path.join(directory, ref))
            if "://" in ref:
                continue
            walk(path) if os.path.isdir(path) else used.add(path)
        inputs = [p["path"] for p in k.get("patches") or [] if isinstance(p, dict) and "path" in p]
        for gen in (k.get("configMapGenerator") or []) + (k.get("secretGenerator") or []):
            inputs += [f.split("=", 1)[-1] for f in (gen.get("files") or []) + (gen.get("envs") or [])]
        used.update(os.path.normpath(os.path.join(directory, p)) for p in inputs)

    for _, ks in kustomizations:
        walk(os.path.normpath(ks["spec"]["path"]))
    return used


def check_embedded_and_grafana(objects, origin):
    """Parses YAML/JSON stored in ConfigMaps, then checks that Grafana's provisioning fits together."""
    dashboards, rules, contact_points, routes = {}, [], set(), []
    datasources = {"__expr__"}  # Grafana's server-side expressions
    for o in objects:
        if o["kind"] == "HelmRelease":
            # The Grafana chart's `datasources` value maps file names to provisioning files.
            provisioned = (o["spec"].get("values") or {}).get("datasources")
            for provisioning in provisioned.values() if isinstance(provisioned, dict) else []:
                if isinstance(provisioning, dict):
                    datasources.update(ds.get("uid") for ds in provisioning.get("datasources") or [])
        if o["kind"] != "ConfigMap":
            continue
        file = origin.get(("ConfigMap", o["metadata"]["name"]))
        for key, text in (o.get("data") or {}).items():
            if not key.endswith((".yaml", ".yml", ".json")):
                continue
            try:
                docs = [json.loads(text)] if key.endswith(".json") else yaml_docs(text)
            except (yaml.YAMLError, json.JSONDecodeError) as exc:
                message, line = parse_error(exc)
                report("error", f"ConfigMap {o['metadata']['name']}, {key} (line {line}): {message}", file)
                continue
            for doc in (d for d in docs if isinstance(d, dict)):
                if doc.get("uid") and "panels" in doc:
                    dashboards[doc["uid"]] = {p.get("id") for p in panels(doc)}
                if doc.get("apiVersion") != 1:
                    continue  # not a Grafana provisioning file
                for group in doc.get("groups") or []:
                    rules += [(file, rule) for rule in group.get("rules") or []]
                contact_points.update(cp.get("name") for cp in doc.get("contactPoints") or [])
                routes += [(file, policy) for policy in doc.get("policies") or []]

    for file, rule in rules:
        title, annotations = rule.get("title"), rule.get("annotations") or {}
        for query in rule.get("data") or []:
            if query.get("datasourceUid") not in datasources:
                report("error", f"alert rule {title!r}: data source {query.get('datasourceUid')!r} is not provisioned", file)
        uid, panel = annotations.get("__dashboardUid__"), annotations.get("__panelId__")
        if uid and uid not in dashboards:
            report("error", f"alert rule {title!r}: dashboard {uid!r} does not exist", file)
        elif uid and panel and int(panel) not in dashboards[uid]:
            report("error", f"alert rule {title!r}: dashboard {uid!r} has no panel {panel}", file)
    print(f"  {len(rules)} alert rules, {len(dashboards)} dashboards, {len(datasources) - 1} data sources, "
          f"{len(contact_points)} contact points, {len(routes)} notification policies")
    while routes:
        file, route = routes.pop()
        if route.get("receiver") and route["receiver"] not in contact_points:
            report("error", f"notification policy uses contact point {route['receiver']!r}, which does not exist", file)
        routes += [(file, child) for child in route.get("routes") or []]


def panels(dashboard):
    for panel in dashboard.get("panels") or []:
        yield panel
        yield from panels(panel)  # rows hold their own panels


def render_helmreleases(objects, origin, flux_location, cache, workdir):
    """Renders every HelmRelease's chart with its values, the way helm-controller installs it."""
    sources = {(o["kind"], o["metadata"].get("namespace"), o["metadata"]["name"]): o for o in objects}
    for hr in (o for o in objects if o["kind"] == "HelmRelease"):
        meta, spec = hr["metadata"], hr["spec"]
        label, file = f"HelmRelease {meta['namespace']}/{meta['name']}", origin.get(("HelmRelease", meta["name"]))
        chart = (spec.get("chart") or {}).get("spec")
        ref = chart["sourceRef"] if chart else spec["chartRef"]
        source = sources.get((ref["kind"], ref.get("namespace", meta["namespace"]), ref["name"]))
        if source is None:
            continue  # reported by check_references
        url = source["spec"]["url"]
        if ref["kind"] == "HelmRepository" and not url.startswith("oci://"):
            args = [chart["chart"], "--repo", url]
        elif ref["kind"] == "HelmRepository":
            args = [f"{url.rstrip('/')}/{chart['chart']}"]
        elif ref["kind"] == "OCIRepository":
            args = [url]
        else:
            report("warning", f"{label}: rendering charts from a {ref['kind']} is not supported here", file)
            continue
        version = chart.get("version") if chart else (source["spec"].get("ref") or {}).get("tag")
        args += ["--version", version] if version else []
        chart_label = f"{chart['chart'] if chart else url} {version or 'latest'}"

        # Helm ignores values a chart doesn't use; that is how Loki and Promtail broke unnoticed. Deeper
        # keys are left alone: charts document many only as comments, and some sections are free-form.
        defaults = run(["helm", "show", "values", *args])
        if defaults.returncode == 0:
            unknown = sorted(set(spec.get("values") or {}) - set(yaml.safe_load(defaults.stdout) or {}))
            if unknown:
                report("warning", f"{label}: {chart_label} has no top-level value {', '.join(unknown)} "
                                  "in its values.yaml; Helm ignores values a chart doesn't use", file)

        for values in spec.get("valuesFrom") or []:
            if values.get("targetPath"):  # the real value lives in the cluster
                args += ["--set-string", f"{values['targetPath']}=from-{values['kind']}-{values['name']}"]
            else:
                report("warning", f"{label}: valuesFrom {values['name']} without targetPath is left out", file)
        values_file = os.path.join(workdir, f"{meta['namespace']}-{meta['name']}-values.yaml")
        with open(values_file, "w", encoding="utf-8") as fh:
            yaml.safe_dump(spec.get("values") or {}, fh)
        namespace = spec.get("targetNamespace") or meta["namespace"]
        release = spec.get("releaseName") or (f"{namespace}-{meta['name']}" if spec.get("targetNamespace") else meta["name"])
        result = run(["helm", "template", release, *args, "--namespace", namespace, "--values", values_file,
                      "--kube-version", KUBERNETES_VERSION, "--include-crds"])
        if result.returncode:
            report("error", f"{label} does not render:\n{result.stderr.strip()}", file)
            continue
        # Charts may create custom resources without published schemas; those are skipped.
        kubeconform(result.stdout, f"{label} ({chart_label})", flux_location, cache, file, ignore_missing=True)


def main():
    os.chdir(subprocess.run(["git", "rev-parse", "--show-toplevel"], capture_output=True, text=True, check=True).stdout.strip())
    files = subprocess.run(["git", "ls-files"], capture_output=True, text=True, check=True).stdout.splitlines()

    section("YAML and JSON syntax")
    check_syntax(files)

    found = list(manifests(files))
    origin = {(d["kind"], d.get("metadata", {}).get("name")): f for f, d in found}
    kustomizations = [(f, d) for f, d in found
                      if d["kind"] == "Kustomization" and d.get("apiVersion", "").startswith("kustomize.toolkit.fluxcd.io/")]

    with tempfile.TemporaryDirectory() as tmp:
        cache = os.path.join(tmp, "cache")
        os.makedirs(cache)
        flux_location = flux_schemas(os.path.join(tmp, "flux"))

        section("Flux Kustomizations: build and schemas")
        objects = build_kustomizations(kustomizations, flux_location, cache)

        section("Flux references")
        check_references(objects, origin)
        used = applied_files(kustomizations)
        print(f"  {len(used)} files applied by Flux")
        for f in files:
            if f.endswith((".yaml", ".yml", ".json")) and not f.startswith(NOT_MANIFESTS) and os.path.normpath(f) not in used:
                report("warning", "no Flux Kustomization applies this file; list it in a kustomization.yaml or delete it", f)

        section("ConfigMap contents and Grafana provisioning")
        check_embedded_and_grafana(objects, origin)

        section("HelmReleases: render and schemas")
        render_helmreleases(objects, origin, flux_location, cache, tmp)

    print(f"\n{problems['error']} error(s), {problems['warning']} warning(s)")
    sys.exit(1 if problems["error"] else 0)


if __name__ == "__main__":
    main()
