# filepath: ./kustomization.yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ingress
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure
    - name: apps
  retryInterval: 5s
  interval: 10m0s
  path: ./ingress
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system