# filepath: ./kustomization.yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: namespaces
  namespace: flux-system
spec:
  interval: 1m0s
  retryInterval: 5s
  path: ./namespaces
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system