apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: kube-system
spec:
  releaseName: traefik
  chart:
    spec:
      chart: traefik
      version: ">=10.0.0"
      sourceRef:
        kind: HelmRepository
        name: traefik-charts
        namespace: flux-system
  values:
    additionalArguments:
      - "--certificatesresolvers.le.acme.email=Arie_Hofland@hotmail.com"
      - "--certificatesresolvers.le.acme.storage=/data/acme.json"
      - "--certificatesresolvers.le.acme.httpchallenge=true"
      - "--certificatesresolvers.le.acme.httpchallenge.entrypoint=web"
    persistence:
      enabled: true
      name: traefik-acme
      accessMode: ReadWriteOnce
      size: 1Gi
      path: /data
      storageClass: default
    ports:
      web:
        expose: true
        port: 80
        protocol: TCP
      websecure:
        expose: true
        port: 443
        protocol: TCP
    ingressRoute:
      dashboard:
        enabled: true
    logs:
      general:
        level: INFO
      access:
        enabled: true