# Create a 1Password item at: vaults/Gembercluster/items/postgresql-admin-secret
# with a field named "postgresPassword" containing the database password.
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: postgresql-admin-secret
  namespace: flux-system
spec:
  itemPath: "vaults/Gembercluster/items/postgresql-admin-secret"
