apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-data-qnap
  namespace: flux-system
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: qnap-nfs
  resources:
    requests:
      storage: 32Gi
