apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: flux-system
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.230   # <-- Add this line
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgresql
  selector:
    app.kubernetes.io/name: postgresql