apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgresql
  namespace: flux-system
spec:
  interval: 10m
  chart:
    spec:
      chart: postgresql
      sourceRef:
        kind: OCIRepository
        name: postgresql-chart
        namespace: flux-system
  values:
    global:
      postgresql:
        auth:
          postgresPassword: "yourStrongPassword" # Change this!
    primary:
      persistence:
        enabled: true
        size: 8Gi
        storageClass: "local-path" # Set to your desired StorageClass, or leave empty for default