apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- externalsecrets
- metallb
- postgresql
- postgresql-backup
- nginx
- certmanager
- nfs-provisioner
- pvcs
- longhorn
- kured
- system-upgrade
