apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - armabotcs
  - ebi-cs-api
  - ebi-cs-frontend
  - vortexplotboek
  - cov-website
  - healthcheck
  - fileserver
  - sts2viewer