apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  annotations:
    flux.weave.works/depends-on: cert-manager:deployment/cert-manager-webhook
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: Arie_Hofland@hotmail.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01:
        ingress:
          ingressClassName: nginx-public
          ingressTemplate:
            metadata:
              annotations:
                nginx.ingress.kubernetes.io/ssl-redirect: "false"
            spec:
              rules:
              - http:
                  paths:
                  - path: /.well-known/acme-challenge
                    pathType: Prefix
                    backend:
                      service:
                        name: cert-manager-acme-http-solver
                        port:
                          number: 8089