apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: discord-secret
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: discord-secret
  data:
    - secretKey: token
      remoteRef:
        key: discord-secret
        property: token