apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: discord-secret
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    namespace: flux-system
    kind: SecretStore
  target:
    name: discord-secret
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: discord-token
      remoteRef:
        key: discord         # Path in Vault (adjust as needed)
        property: token   # Key in Vault secret