apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-secret
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    namespace: flux-system
    kind: SecretStore
  target:
    name: grafana-secret
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: grafana-password
      remoteRef:
        key: grafana         # Path in Vault (adjust as needed)
        property: password   # Key in Vault secret