apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-secret
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: grafana-secret
  data:
    - secretKey: user
      remoteRef:
        key: grafana-secret
        property: user
    - secretKey: password
      remoteRef:
        key: grafana-secret
        property: password