apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.1.230-192.168.1.239
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2lbadv
  namespace: metallb-system
spec:
  ipAddressPools:
  - first-pool
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: default-ip-whitelist
  namespace: mysql   # <-- Add this line
spec:
  ipWhiteList:
    sourceRange:
      - 10.0.0.0/8     # Your VPN or local network
      - 192.168.0.0/16  