apiVersion: external-secrets.io/v1  # Use v1beta1 if that's what your operator supports
kind: ExternalSecret
metadata:
  name: postgresql-secret
  namespace: flux-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: postgresql-secret
    creationPolicy: Owner   # Ensures the secret is deleted if the ExternalSecret is deleted
    deletionPolicy: Retain  # Keeps the secret if the provider data is deleted
  data:
    - secretKey: postgresPassword
      remoteRef:
        key: kv/postgress      # Path in Vault (strip /v1/ and /data/)
        property: password     # Key in Vault secret