apiVersion: external-secrets.io/v1  # Use v1beta1 if that's what your operator supports
kind: ExternalSecret
metadata:
  name: postgresql-connection-secret
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: postgresql-connection-secret
    creationPolicy: Owner   # Ensures the secret is deleted if the ExternalSecret is deleted
    deletionPolicy: Retain  # Keeps the secret if the provider data is deleted
  data:
    - secretKey: postgres-connectionstring
      remoteRef:
        key: postgress
        property: connectionstring
