apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgress-secret
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: postgress-secret
  data:
    - secretKey: connectionstring
      remoteRef:
        key: postgress-secret
        property: connectionstring
