apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: postgresql-secret
  namespace: flux-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: postgresql-secret
  data:
    - secretKey: postgresPassword
      remoteRef:
        key: kv/postgress      # <-- matches your Vault path (strip /v1/ and /data/)
        property: password     # <-- matches your Vault key