apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: onepassword
spec:
  provider:
    onepassword:
      auth:
        secretRef:
          name: op-service-account
          key: service-account.json
          namespace: flux-system