apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: onepassword
spec:
  provider:
    onepassword:
      auth:
        secretRef:
          serviceAccountTokenSecretRef:
            name: op-service-account
            key: service-account.json
            namespace: flux-system