apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-backend
  namespace: flux-system
spec:
  provider:
    vault:
      server: "http://vault.flux-system.svc.cluster.local:8200"
      path: "kv"           # Use "kv" if your Vault mount is at /v1/kv/...
      version: "v2"
      auth:
        tokenSecretRef:
          name: vault-token
          key: token
          namespace: flux-system   # <-- Add this line          