apiVersion: v1
kind: Service
metadata:
  name: dungeontable-service
  namespace: dungeontable
spec:
  type: ClusterIP
  selector:
    app: dungeontable
  ports:
    - name: http
      port: 80
      targetPort: 8080
