apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: postgress-vortexplotboek-secret
  namespace: vortexplotboek 
spec:
  itemPath: "vaults/Gembercluster/items/postgress-vortexplotboek-secret"