apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-backup-pvc-qnap
  namespace: flux-system
spec:
  storageClassName: qnap-nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
